k: 32
sz: 256
ch: 9
ps: 64
LR: 3e-4 
BETA1: 0.9
BETA2: 0.999
WEIGHT_DECAY: 0.5
NUM_GPU: 2
DATASET_NAME: RenderedWB
DATASET_ROOT: "/media/birdortyedi/e5042b8f-ca5e-4a22-ac68-7e69ff648bc4/RenderedWB/"
BACKBONE_TYPE: "mixed_wb"
BACKBONE_WEIGHTS_PATH: "weights/mixed_wb/mixed_wb_64_9.pth"
IMG_SIZE: 256
INIT_FROM: null
BATCH_SIZE: 16
EPOCHS: 200
LAMBDA: 100
SCHEDULER_STEP: 160
SCHEDULER_GAMMA: 0.1
VISUALIZE_STEP: 50
SHUFFLE: True
NUM_WORKERS: 4
CKPT_DIR: "./ckpts"
PROJECT_NAME: "neural-preset-awb-pytorch"
LOG_DIR: "./logs"
ENTITY: "vvgl-ozu"